### PR TITLE
depend on specific version of ffmmpeg packages

### PR DESCRIPTION
**Pull request by tspicer01**
Add dependency on specific version of ffmmpeg packages

### CODE REVIEW

**Comment by tspicer01** [comment]
Initial workspace testing done but need to pull it into a bundle to ensure that the dependencies are being seen properly.

**Comment by mikepurvis** [comment]
You can use the prep flag to validate that it ends up in the control file correctly.

**Review by mikepurvis — APPROVED** [review]

**Comment by tspicer01** [comment]
I just checked my workspace and it may not have worked.

ldd cv2.so | grep libav
        libavcodec.so.54 => /usr/lib/x86_64-linux-gnu/libavcodec.so.54 (0x00007fb33a07b000)
        libavformat.so.54 => /usr/lib/x86_64-linux-gnu/libavformat.so.54 (0x00007fb339d59000)
        libavutil.so.52 => /usr/lib/x86_64-linux-gnu/libavutil.so.52 (0x00007fb339b34000)

**Comment by mikepurvis** [comment]
IIRC the `libavcodec-dev` package from that PPA was pulling in _both_ `libavcodec54` and `libavcodec56`, so I'm not sure what exactly was going on under the hood there.

**Pull request merged**
